# Generated by Django 3.2.16 on 2023-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230410_1430'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(False), name='check_user'),
        ),
    ]
