# Generated by Django 3.2.16 on 2023-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230410_1439'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user__gta', 'following')), name='check_user'),
        ),
    ]
