# Generated by Django 3.2.16 on 2023-04-10 11:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230410_1450'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='check_user'),
        ),
    ]
