# Generated by Django 3.2.16 on 2023-04-10 11:56

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230410_1455'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following', django.db.models.expressions.F('user')), _negated=True), name='check_follow'),
        ),
    ]
