# Generated by Django 3.2.16 on 2023-04-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20230410_1456'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_follow',
        ),
    ]
