# Generated by Django 3.2.16 on 2023-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20230411_1310'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following', 'user')), name='check_follow'),
        ),
    ]
