# Generated by Django 3.2.16 on 2023-04-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20230411_1412'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following', 'follower')), name='check_following'),
        ),
    ]
