# Generated by Django 3.2.16 on 2023-04-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20230411_1422'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_following',
        ),
    ]
