# Generated by Django 3.2.16 on 2023-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_follow_check_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user__gte', 'following'), _negated=True), name='user__gte_following'),
        ),
    ]
